name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Download bin
        run: |
          # TODO
          #url="https://github.com/owner/repository/releases/download/v${{ env.VERSION }}/package-${{ env.VERSION }}.linux-amd64.tar.gz"
          #wget -O- ${url} | tar xz --strip-components=1 -C ./deb/opt/vyatta-TEMPLATE

      - name: Adjust version number for release
        if: startsWith(github.ref, 'refs/tags/')
        run: |
          sed -i "s|Version:.*|Version: ${GITHUB_REF#refs/*v}|" ./deb/DEBIAN/control

      - name: Build deb
        run: |
          chmod +x deb/DEBIAN/postinst
          dpkg-deb --build --root-owner-group deb

      - name: Rename deb
        run: mv deb.deb vyatta-TEMPLATE_$(dpkg-deb -f deb.deb Version)_$(dpkg-deb -f deb.deb Architecture).deb

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: debian-vyatta-node_exporter
          path: "vyatta-TEMPLATE_*.deb"

      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["vyatta-TEMPLATE_*.deb"]'
