name: CI

on:
  push:
    branches: [main]
    tags: ["v*"]
  pull_request:

env:
  VERSION: 1.0.0

jobs:
  build:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v3

      - name: Build deb
        run: |
          chmod +x deb/DEBIAN/postinst
          dpkg-deb --build --root-owner-group deb

      - name: Rename deb
        run: mv deb.deb vyatta-web_$(dpkg-deb -f deb.deb Version)_$(dpkg-deb -f deb.deb Architecture).deb

      - name: Upload deb
        uses: actions/upload-artifact@v3
        with:
          name: debian-vyatta-web
          path: "vyatta-web_*.deb"

      - uses: alexellis/upload-assets@0.4.0
        if: startsWith(github.ref, 'refs/tags/')
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          asset_paths: '["vyatta-web_*.deb"]'
